data_path: '/home/pedro/Documents/Documents/projects/pointcloud/h3d/2019/data_corrected/down/'
features_to_use:
  - surface_variation
  - sphericity
  - verticality

transdict:
  0: 0  # unclassified -> unclassified
  1: 1  # ground -> ground
  2: 0  # low vegetation -> unclassified
  3: 0  # medium vegetation -> unclassified
  4: 2  # roof -> roofss
  5: 0  # building -> unclassified
  6: 0  # noise -> unclassified
  7: 0  # bridge deck -> unclassified
  8: 0  # high point -> unclassified
  9: 0  # water -> unclassified
  
model_name: 'xgboost'  
model_output_path: '/home/pedro/Documents/Documents/projects/pointcloud/zim_results/ml_models/trained_model/xg_3c_pkl'   

