shapefile_path: './input/object_extractions_Maibach/object_extractions/v3/street_pg.shp'

polygon_type:
  - street_paved
  - sidewalk

point_cloud_path: './output/maibach_ground.las'

output_las: './output/maibach_street.las'

buffer_distance: 0.3
