shapefile_path: '/home/pedro/Documents/Documents/projects/pointcloud/zim_results/inputs/object_extractions_Poppenhausen/object_extractions/v3/street_pg.shp'

polygon_type:
  - street_paved
  - sidewalk

point_cloud_path: '/home/pedro/Documents/Documents/projects/pointcloud/zim_results/output/poppenhausen_ground.las'

output_las: '/home/pedro/Documents/Documents/projects/pointcloud/zim_results_docker/output/poppenhausen_street.las'

buffer_distance: 0.0
