pcd_path: './output/maibach_street.las'
model_path: './models/curb_rf_final_26.pkl'
output_path: "./output/maibach_curb_inference.las"
crs: "EPSG:25832"
saturation_filter: 0.15
probability_threshold: 0.6