input_las: "./input/Maibach_pointcloud_highquality_downsampled.las"  # Replace with your LAS file path
input_dem: "./output/maibach_ground_final.tif"  # Output mesh file
output_las: "./output/maibach_hag.las"  # Output mesh file